### ISSUE TITLE
Don't run. An Error is there.

### ISSUE THREAD

**Issue by jmupz** [jmuelbert/jmopenorders#21]
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\jmopenorders.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\jmopenorders\__main__.py", line 134, in main
    berater = names.get()
  File "c:\python37\lib\site-packages\jmopenorders\openorders\getserviceperson.py", line 76, in get
    berater_file.close()
UnboundLocalError: local variable 'berater_file' referenced before assignment

**Comment by jmuelbert** [comment]
The Code is changed. Should run now.

Thank you for testing.
